# Generated by Django 4.2.14 on 2024-07-29 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalanceStoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=10, max_digits=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('type_balance', models.CharField(choices=[('Вам перевели деньги', 'Received Transfer'), ('Вы перевели деньги', 'Made Transfer')], default='Вы перевели деньги', max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
